include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.gr.dart
    - lib/**.config.dart
    - lib/**.freezed.dart
  errors:
    todo: ignore
    fixme: ignore