name: database_service
description: A database broker for no-sql and sql databases
version: 3.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.20.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
